import type { RoArmourPiece } from "./msq-types";

/** Shared Noblesse garments / footwear / rings (all classes can wear these). */
const NOBLESSE_SHARED: readonly RoArmourPiece[] = [
  {
    id: 480012,
    name: "Noblesse Attack Manteau [1]",
    flavor: "A noble manteau with the Rune-Midgarts crest engraved on it.",
    effects: [
      "ASPD +3%",
      "If refined to +7 or higher: After Cast Delay -5%",
      "If refined to +9 or higher: Physical damage +5% vs all sizes",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "20",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "100",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "1",
    upgradeTicket: "Noblesse Upgrade Ticket",
  },
  {
    id: 480014,
    name: "Noblesse Magic Manteau [1]",
    flavor: "A noble manteau tuned for spellcasting, with the Rune-Midgarts crest.",
    effects: [
      "Variable Cast Time -5%",
      "If refined to +7 or higher: After Cast Delay -5%",
      "If refined to +9 or higher: All elemental magic damage +5%",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "20",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "100",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "1",
    upgradeTicket: "Noblesse Upgrade Ticket",
  },
  {
    id: 470016,
    name: "Noblesse Attack Boots [1]",
    flavor: "Noblesse footwear tuned for the physical attack set.",
    effects: [
      "ATK +10",
      "HIT +10",
      "If refined to +7 or higher: Fixed Cast Time -0.5 sec",
      "If refined to +9 or higher: Long-ranged physical damage +5%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "20",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "100",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "1",
    upgradeTicket: "Noblesse Upgrade Ticket",
  },
  {
    id: 470017,
    name: "Noblesse Magic Boots [1]",
    flavor: "Noblesse footwear tuned for the magic set.",
    effects: [
      "MATK +10",
      "FLEE +10",
      "If refined to +7 or higher: Fixed Cast Time -0.5 sec",
      "If refined to +9 or higher: All elemental magic damage +5%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "20",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "100",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "1",
    upgradeTicket: "Noblesse Upgrade Ticket",
  },
  {
    id: 490014,
    name: "Noblesse Attack Ring [1]",
    flavor: "A ring bearing the crest of the Noblesse attack branch.",
    effects: ["ASPD +3%", "Variable Cast Time -5%", "Critical Damage +5%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "5",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "100",
    jobs: "All Jobs",
    location: "Accessory",
    armorLevel: "1",
    upgradeTicket: "Noblesse Upgrade Ticket",
  },
  {
    id: 490015,
    name: "Noblesse Magic Ring [1]",
    flavor: "A ring bearing the crest of the Noblesse magic branch.",
    effects: ["ASPD +3%", "Variable Cast Time -5%", "Magic damage +5% vs all elements"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "5",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "100",
    jobs: "All Jobs",
    location: "Accessory",
    armorLevel: "1",
    upgradeTicket: "Noblesse Upgrade Ticket",
  },
];

type NoblesseBody = {
  id: number;
  name: string;
  jobs: string;
  defense: "100" | "70";
  focus: string;
};

/** Class-specific Noblesse body armors (Noblesse Trader, Honor Tokens) — see iRO Wiki Noblesse Equipment. */
const NOBLESSE_BODIES: readonly NoblesseBody[] = [
  { id: 450019, name: "Noblesse Knight Armor [1]", jobs: "Rune Knight classes", defense: "100", focus: "Ignition Break (Attack set)" },
  { id: 450018, name: "Noblesse Breath Armor [1]", jobs: "Rune Knight classes", defense: "100", focus: "Dragon Breath / Dragon Water Breath (Attack set)" },
  { id: 450020, name: "Noblesse Spear Armor [1]", jobs: "Royal Guard classes", defense: "100", focus: "Cannon Spear (Attack set)" },
  { id: 450021, name: "Noblesse Genesis Armor [1]", jobs: "Royal Guard classes", defense: "100", focus: "Genesis Ray (Magic garment/boots/ring)" },
  { id: 450040, name: "Noblesse Crimson Robe [1]", jobs: "Warlock classes", defense: "70", focus: "Crimson Rock (Magic set)" },
  { id: 450041, name: "Noblesse Frost Robe [1]", jobs: "Warlock classes", defense: "70", focus: "Jack Frost (Magic set)" },
  { id: 450042, name: "Noblesse Psychic Robe [1]", jobs: "Sorcerer classes", defense: "70", focus: "Psychic Wave (Magic set)" },
  { id: 450043, name: "Noblesse Dust Robe [1]", jobs: "Sorcerer classes", defense: "70", focus: "Diamond Dust (Magic set)" },
  { id: 450022, name: "Noblesse Sharp Suit [1]", jobs: "Ranger classes", defense: "70", focus: "Focused Arrow Strike (Attack set)" },
  { id: 450023, name: "Noblesse Aim Suit [1]", jobs: "Ranger classes", defense: "70", focus: "Aimed Bolt (Attack set)" },
  { id: 450024, name: "Noblesse Severe Suit [1]", jobs: "Maestro / Wanderer classes", defense: "70", focus: "Severe Rainstorm (Attack set)" },
  { id: 450025, name: "Noblesse Reverberation Suit [1]", jobs: "Maestro / Wanderer classes", defense: "70", focus: "Reverberation (Magic set)" },
  { id: 450028, name: "Noblesse Tornado Armor [1]", jobs: "Mechanic classes", defense: "70", focus: "Axe Tornado (Attack set)" },
  { id: 450029, name: "Noblesse Vulcan Armor [1]", jobs: "Mechanic classes", defense: "70", focus: "Vulcan Arm (Attack set)" },
  { id: 450030, name: "Noblesse Cart Cannon Suit [1]", jobs: "Geneticist classes", defense: "70", focus: "Cart Cannon (Attack set)" },
  { id: 450031, name: "Noblesse Cart Tornado Suit [1]", jobs: "Geneticist classes", defense: "70", focus: "Cart Tornado (Attack set)" },
  { id: 450032, name: "Noblesse Rolling Suit [1]", jobs: "Guillotine Cross classes", defense: "70", focus: "Rolling Cutter (Attack set)" },
  { id: 450033, name: "Noblesse Assassin Suit [1]", jobs: "Guillotine Cross classes", defense: "70", focus: "Critical / physical (Attack set)" },
  { id: 450034, name: "Noblesse Fatal Suit [1]", jobs: "Shadow Chaser classes", defense: "70", focus: "Fatal Menace (Attack set)" },
  { id: 450035, name: "Noblesse Stalker Suit [1]", jobs: "Shadow Chaser classes", defense: "70", focus: "Meteor Storm (Magic set)" },
  { id: 450027, name: "Noblesse Duple Robe [1]", jobs: "Arch Bishop classes", defense: "70", focus: "Duple Light (Attack set)" },
  { id: 450026, name: "Noblesse Adora Robe [1]", jobs: "Arch Bishop classes", defense: "70", focus: "Adoramus (Magic set)" },
  { id: 450050, name: "Noblesse Knuckle Suit [1]", jobs: "Sura classes", defense: "70", focus: "Knuckle Arrow (Attack set)" },
  { id: 450051, name: "Noblesse Tiger Cannon Suit [1]", jobs: "Sura classes", defense: "70", focus: "Tiger Cannon (Attack set)" },
  { id: 450045, name: "Noblesse Full Moon Suit [1]", jobs: "Star Emperor classes", defense: "70", focus: "Full Moon Kick (Attack set)" },
  { id: 450044, name: "Noblesse Sun Suit [1]", jobs: "Star Emperor classes", defense: "70", focus: "Solar Explosion (Attack set)" },
  { id: 450049, name: "Noblesse Curse Robe [1]", jobs: "Soul Reaper classes", defense: "70", focus: "Curse Explosion (Magic set)" },
  { id: 450048, name: "Noblesse Eswoo Robe [1]", jobs: "Soul Reaper classes", defense: "70", focus: "Eswoo (Magic set)" },
  { id: 450047, name: "Noblesse Kunai Suit [1]", jobs: "Ninja classes", defense: "70", focus: "Kunai Splash (Attack set)" },
  { id: 450046, name: "Noblesse Ninja Suit [1]", jobs: "Ninja classes", defense: "70", focus: "Magic ninja skills (Magic set)" },
  { id: 450038, name: "Noblesse Trip Suit [1]", jobs: "Rebel classes", defense: "70", focus: "Round Trip (Attack set)" },
  { id: 450039, name: "Noblesse Fire Rain Suit [1]", jobs: "Rebel classes", defense: "70", focus: "Fire Rain (Attack set)" },
  { id: 450121, name: "Noblesse Super Novice Suit [1]", jobs: "Novice / Super Novice classes", defense: "70", focus: "Physical Super Novice (Attack set)" },
  { id: 450122, name: "Noblesse Super Novice Robe [1]", jobs: "Novice / Super Novice classes", defense: "70", focus: "Magical Super Novice (Magic set)" },
  { id: 450036, name: "Noblesse Picky Robe [1]", jobs: "Summoner (Doram) classes", defense: "70", focus: "Picky Peck (Attack set)" },
  { id: 450037, name: "Noblesse Catnip Robe [1]", jobs: "Summoner (Doram) classes", defense: "70", focus: "Catnip Meteor (Magic set)" },
];

function noblesseBody(p: NoblesseBody): RoArmourPiece {
  const short = p.name.replace(" [1]", "");
  return {
    id: p.id,
    name: p.name,
    flavor: `${short} — exchanged from Noblesse Trader (Prontera Castle) for Honor Tokens.`,
    effects: [
      `Class / skill focus: ${p.focus}.`,
      "Four-piece Noblesse bonuses use the matching Attack or Magic manteau, boots, and ring (see iRO Wiki: Noblesse Equipment).",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: p.defense,
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "100",
    jobs: p.jobs,
    location: "Body",
    armorLevel: "1",
    upgradeTicket: "Noblesse Upgrade Ticket",
  };
}

/** Full Noblesse armour list: shared slots first, then every class body armor. */
export const NOBLESSE_ARMOUR_PIECES: readonly RoArmourPiece[] = [...NOBLESSE_SHARED, ...NOBLESSE_BODIES.map(noblesseBody)];
