import type { MsqWeaponSegment } from "./msq-types";

/**
 * Issgard Glacier weapons — stats from rAthena `item_db_equip.yml` (aligned with Divine Pride iRO).
 * Shop line: 150,000 zeny NPC. Dim line: level 230 drops with [1] slot.
 * Regenerate: `node scripts/gen-msq-glacier-weapons.mjs` (requires `%TEMP%\\item_db_equip.yml`).
 */
export const GLACIER_WEAPON_SEGMENTS: readonly MsqWeaponSegment[] = [
  {
    segmentName: "Glacier (shop)",
    pieces: [
  {
    id: 500049,
    name: 'Glacier Sword',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Sword',
    attack: '220',
    matk: '+210',
    weight: '16',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Alchemist, Blacksmith, Crusader, Knight, Merchant, Swordsman',
    location: 'Right Hand',
  },
  {
    id: 500050,
    name: 'Glacier Basic Sword',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Sword',
    attack: '220',
    matk: '+210',
    weight: '14',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Novice, Super Novice',
    location: 'Right Hand',
  },
  {
    id: 510061,
    name: 'Glacier Rogue Knife',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Dagger',
    attack: '210',
    matk: '+210',
    weight: '14',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Rogue',
    location: 'Right Hand',
  },
  {
    id: 510062,
    name: 'Glacier Basic Knife',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Dagger',
    attack: '210',
    matk: '+210',
    weight: '12',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Novice, Super Novice',
    location: 'Right Hand',
  },
  {
    id: 520017,
    name: 'Glacier Axe',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Axe',
    attack: '240',
    matk: '+210',
    weight: '50',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Alchemist, Blacksmith, Crusader, Knight, Merchant, Swordsman',
    location: 'Right Hand',
  },
  {
    id: 530025,
    name: 'Glacier Spear',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Spear',
    attack: '220',
    matk: '+210',
    weight: '21',
    weaponLevel: '5',
    range: '3',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Crusader, Knight, Swordsman',
    location: 'Right Hand',
  },
  {
    id: 540049,
    name: 'Glacier Book',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Book',
    attack: '210',
    matk: '+210',
    weight: '12',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Priest, Sage, Star Gladiator',
    location: 'Right Hand',
  },
  {
    id: 550069,
    name: 'Glacier Wand',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Staff',
    attack: '150',
    matk: '+230',
    weight: '13',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Novice, Mage, Acolyte, Priest, Wizard, Monk, Sage, Super Novice, Soul Linker',
    location: 'Right Hand',
  },
  {
    id: 550070,
    name: 'Glacier Foxtail Staff',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Staff',
    attack: '400',
    matk: '+400',
    weight: '20',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Summoner',
    location: 'Right Hand',
  },
  {
    id: 560032,
    name: 'Glacier Knuckle',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Knuckle',
    attack: '240',
    matk: '+220',
    weight: '15',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Monk',
    location: 'Right Hand',
  },
  {
    id: 570029,
    name: 'Glacier Violin',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Instrument',
    attack: '210',
    matk: '+210',
    weight: '15',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Bard / Dancer',
    location: 'Right Hand',
  },
  {
    id: 580030,
    name: 'Glacier Whip',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Whip',
    attack: '210',
    matk: '+210',
    weight: '15',
    weaponLevel: '5',
    range: '2',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Bard / Dancer',
    location: 'Right Hand',
  },
  {
    id: 590038,
    name: 'Glacier Mace',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Mace',
    attack: '210',
    matk: '+210',
    weight: '18',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Acolyte, Alchemist, Blacksmith, Crusader, Knight, Merchant, Monk, Priest, Swordsman',
    location: 'Right Hand',
  },
  {
    id: 590039,
    name: 'Glacier Mechanic Mace',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Mace',
    attack: '400',
    matk: '+160',
    weight: '40',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Blacksmith',
    location: 'Right Hand',
  },
  {
    id: 600027,
    name: 'Glacier Two-Handed Sword',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Two-Handed Sword',
    attack: '300',
    matk: '+270',
    weight: '40',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Knight',
    location: 'Both Hand',
  },
  {
    id: 610037,
    name: 'Glacier Katar',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Katar',
    attack: '240',
    matk: '+220',
    weight: '12',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Assassin',
    location: 'Both Hand',
  },
  {
    id: 620017,
    name: 'Glacier Two-Handed Axe',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Two-Handed Axe',
    attack: '350',
    matk: '+180',
    weight: '70',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Blacksmith',
    location: 'Both Hand',
  },
  {
    id: 630018,
    name: 'Glacier Lance',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Two-Handed Spear',
    attack: '300',
    matk: '+270',
    weight: '45',
    weaponLevel: '5',
    range: '3',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Knight',
    location: 'Both Hand',
  },
  {
    id: 640033,
    name: 'Glacier Staff',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Two-Handed Staff',
    attack: '150',
    matk: '+290',
    weight: '24',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Acolyte, Mage, Monk, Priest, Sage, Soul Linker, Wizard',
    location: 'Both Hand',
  },
  {
    id: 650025,
    name: 'Glacier Huuma',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Huuma Shuriken',
    attack: '400',
    matk: '+370',
    weight: '30',
    weaponLevel: '5',
    range: '1',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Kagerou / Oboro',
    location: 'Both Hand',
  },
  {
    id: 700052,
    name: 'Glacier Bow',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Bow',
    attack: '240',
    weight: '15',
    weaponLevel: '5',
    range: '5',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Archer, Bard / Dancer, Hunter, Rogue',
    location: 'Both Hand',
  },
  {
    id: 800014,
    name: 'Glacier Revolver',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Revolver',
    attack: '230',
    weight: '22',
    weaponLevel: '5',
    range: '7',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Rebellion',
    location: 'Both Hand',
  },
  {
    id: 810010,
    name: 'Glacier Rifle',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Rifle',
    attack: '280',
    weight: '26',
    weaponLevel: '5',
    range: '9',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Gunslinger, Rebellion',
    location: 'Both Hand',
  },
  {
    id: 820008,
    name: 'Glacier Shotgun',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Shotgun',
    attack: '300',
    weight: '26',
    weaponLevel: '5',
    range: '9',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Rebellion',
    location: 'Both Hand',
  },
  {
    id: 830013,
    name: 'Glacier Gatling',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Gatling Gun',
    attack: '350',
    weight: '35',
    weaponLevel: '5',
    range: '9',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Rebellion',
    location: 'Both Hand',
  },
  {
    id: 840009,
    name: 'Glacier Launcher',
    flavor: 'Ice weapon from Issgard’s glaciers, enchantable with Ice Flower Magic Stones (per Divine Pride / iRO).',
    effects: [
      'No card slot; up to four Glacier Flower Spell enchant lines (iRO Wiki: Issgard weapon enchants).',
      'Sold by NPC in Issgard for 150,000 zeny (Free-to-play Equipment — Issgard 19).',
    ],
    equipType: 'Weapon',
    subtype: 'Grenade Launcher',
    attack: '300',
    weight: '30',
    weaponLevel: '5',
    range: '9',
    slots: 'None',
    refineable: 'Yes',
    requiredLevel: '210',
    jobs: 'Rebellion',
    location: 'Both Hand',
  },
    ],
  },
  {
    segmentName: "Dim Glacier (drops)",
    pieces: [
  {
    id: 500054,
    name: 'Dim Glacier Sword',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Sword',
    attack: '220',
    matk: '+210',
    weight: '16',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Alchemist, Blacksmith, Crusader, Knight, Merchant, Swordsman',
    location: 'Right Hand',
  },
  {
    id: 500055,
    name: 'Dim Glacier Basic Sword',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Sword',
    attack: '220',
    matk: '+210',
    weight: '14',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Novice, Super Novice',
    location: 'Right Hand',
  },
  {
    id: 510075,
    name: 'Dim Glacier Rogue Knife',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Dagger',
    attack: '210',
    matk: '+210',
    weight: '14',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Rogue',
    location: 'Right Hand',
  },
  {
    id: 510076,
    name: 'Dim Glacier Basic Knife',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Dagger',
    attack: '210',
    matk: '+210',
    weight: '12',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Novice, Super Novice',
    location: 'Right Hand',
  },
  {
    id: 520021,
    name: 'Dim Glacier Axe',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Axe',
    attack: '240',
    matk: '+210',
    weight: '50',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Alchemist, Blacksmith, Crusader, Knight, Merchant, Swordsman',
    location: 'Right Hand',
  },
  {
    id: 530034,
    name: 'Dim Glacier Spear',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Spear',
    attack: '220',
    matk: '+210',
    weight: '21',
    weaponLevel: '5',
    range: '3',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Crusader, Knight, Swordsman',
    location: 'Right Hand',
  },
  {
    id: 540056,
    name: 'Dim Glacier Book',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Book',
    attack: '210',
    matk: '+210',
    weight: '12',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Priest, Sage, Star Gladiator',
    location: 'Right Hand',
  },
  {
    id: 550089,
    name: 'Dim Glacier Wand',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Staff',
    attack: '150',
    matk: '+230',
    weight: '13',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Acolyte, Mage, Monk, Novice, Super Novice, Priest, Sage, Soul Linker, Wizard',
    location: 'Right Hand',
  },
  {
    id: 550090,
    name: 'Dim Glacier Foxtail',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Staff',
    attack: '400',
    matk: '+400',
    weight: '20',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Summoner',
    location: 'Right Hand',
  },
  {
    id: 560037,
    name: 'Dim Glacier Knuckle',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Knuckle',
    attack: '240',
    matk: '+220',
    weight: '15',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Monk',
    location: 'Right Hand',
  },
  {
    id: 570032,
    name: 'Dim Glacier Violin',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Instrument',
    attack: '210',
    matk: '+210',
    weight: '15',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Bard / Dancer',
    location: 'Right Hand',
  },
  {
    id: 580033,
    name: 'Dim Glacier Whip',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Whip',
    attack: '210',
    matk: '+210',
    weight: '15',
    weaponLevel: '5',
    range: '2',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Bard / Dancer',
    location: 'Right Hand',
  },
  {
    id: 590047,
    name: 'Dim Glacier Mace',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Mace',
    attack: '210',
    matk: '+210',
    weight: '18',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Acolyte, Alchemist, Blacksmith, Crusader, Knight, Merchant, Monk, Priest, Swordsman',
    location: 'Right Hand',
  },
  {
    id: 590048,
    name: 'Dim Glacier Mechanic Mace',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Mace',
    attack: '400',
    matk: '+160',
    weight: '40',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Blacksmith',
    location: 'Right Hand',
  },
  {
    id: 600030,
    name: 'Dim Glacier Two-handed Sword',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Two-Handed Sword',
    attack: '300',
    matk: '+270',
    weight: '40',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Knight',
    location: 'Both Hand',
  },
  {
    id: 610041,
    name: 'Dim Glacier Katar',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Katar',
    attack: '240',
    matk: '+220',
    weight: '12',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Assassin',
    location: 'Both Hand',
  },
  {
    id: 620019,
    name: 'Dim Glacier Mechanic Axe',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Two-Handed Axe',
    attack: '350',
    matk: '+180',
    weight: '70',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Blacksmith',
    location: 'Both Hand',
  },
  {
    id: 630019,
    name: 'Dim Glacier Lance',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Two-Handed Spear',
    attack: '300',
    matk: '+270',
    weight: '45',
    weaponLevel: '5',
    range: '3',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Knight',
    location: 'Both Hand',
  },
  {
    id: 640034,
    name: 'Dim Glacier Staff',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Two-Handed Staff',
    attack: '150',
    matk: '+290',
    weight: '24',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Acolyte, Mage, Monk, Priest, Sage, Soul Linker, Wizard',
    location: 'Both Hand',
  },
  {
    id: 650028,
    name: 'Dim Glacier Huuma Shuriken',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Huuma Shuriken',
    attack: '400',
    matk: '+370',
    weight: '30',
    weaponLevel: '5',
    range: '1',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Kagerou / Oboro',
    location: 'Both Hand',
  },
  {
    id: 700059,
    name: 'Dim Glacier Bow',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Bow',
    attack: '240',
    weight: '15',
    weaponLevel: '5',
    range: '5',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Archer, Bard / Dancer, Hunter, Rogue',
    location: 'Both Hand',
  },
  {
    id: 800015,
    name: 'Dim Glacier Pistol',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Revolver',
    attack: '230',
    weight: '22',
    weaponLevel: '5',
    range: '7',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Rebellion',
    location: 'Both Hand',
  },
  {
    id: 810015,
    name: 'Dim Glacier Rifle',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Rifle',
    attack: '280',
    weight: '26',
    weaponLevel: '5',
    range: '9',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Rebellion',
    location: 'Both Hand',
  },
  {
    id: 820011,
    name: 'Dim Glacier Shotgun',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Shotgun',
    attack: '300',
    weight: '26',
    weaponLevel: '5',
    range: '9',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Rebellion',
    location: 'Both Hand',
  },
  {
    id: 830015,
    name: 'Dim Glacier Gatling Gun',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Gatling Gun',
    attack: '350',
    weight: '35',
    weaponLevel: '5',
    range: '9',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Rebellion',
    location: 'Both Hand',
  },
  {
    id: 840010,
    name: 'Dim Glacier Grenade Launcher',
    flavor: 'Dim glacier-forged weapon from Issgard; stronger requirement than the shop line, with a card slot and Dim-only enchant layout.',
    effects: [
      '[1] Card slot; three enchant lines — Slot{2} uses its own level 1–5 track (iRO Wiki).',
      'Monster drops: Abandoned Pit (jor_ab01 / jor_ab02) or Warmth of the Serpent God (jor_dun01 / jor_dun02).',
      'Unwanted copies can be extracted for Snow Flower / mana ores (see Issgard enchants on iRO Wiki).',
    ],
    equipType: 'Weapon',
    subtype: 'Grenade Launcher',
    attack: '300',
    weight: '30',
    weaponLevel: '5',
    range: '9',
    slots: '[1]',
    refineable: 'Yes',
    requiredLevel: '230',
    jobs: 'Rebellion',
    location: 'Both Hand',
  },
    ],
  },
];
