import type { RoArmourPiece } from "./msq-types";

/** Shared Imperial garments / footwear / rings (all classes can wear these). */
const IMPERIAL_SHARED: readonly RoArmourPiece[] = [
  {
    id: 480016,
    name: "Imperial Attack Manteau [1]",
    flavor: "Imperial manteau for the physical attack set (Schwartz's Honor Token exchange).",
    effects: [
      "ASPD +5%",
      "If refined to +7 or higher: After Cast Delay -5%",
      "If refined to +9 or higher: Physical damage +7% vs all sizes",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "25",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "125",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "1",
    upgradeTicket: "Imperial Upgrade Ticket",
  },
  {
    id: 480017,
    name: "Imperial Magic Manteau [1]",
    flavor: "Imperial manteau for the magic set (Schwartz's Honor Token exchange).",
    effects: [
      "Variable Cast Time -7%",
      "If refined to +7 or higher: After Cast Delay -5%",
      "If refined to +9 or higher: All elemental magic damage +7%",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "25",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "125",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "1",
    upgradeTicket: "Imperial Upgrade Ticket",
  },
  {
    id: 470018,
    name: "Imperial Attack Boots [1]",
    flavor: "Imperial footwear for the physical attack set.",
    effects: [
      "ATK +15",
      "HIT +15",
      "If refined to +7 or higher: Fixed Cast Time -0.5 sec",
      "If refined to +9 or higher: Long-ranged physical damage +7%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "25",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "125",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "1",
    upgradeTicket: "Imperial Upgrade Ticket",
  },
  {
    id: 470019,
    name: "Imperial Magic Boots [1]",
    flavor: "Imperial footwear for the magic set.",
    effects: [
      "MATK +15",
      "FLEE +15",
      "If refined to +7 or higher: Fixed Cast Time -0.5 sec",
      "If refined to +9 or higher: All elemental magic damage +7%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "25",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "125",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "1",
    upgradeTicket: "Imperial Upgrade Ticket",
  },
  {
    id: 490017,
    name: "Imperial Attack Ring [1]",
    flavor: "Imperial ring for the physical attack set.",
    effects: ["ASPD +5%", "Variable Cast Time -7%", "Critical Damage +7%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "8",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "125",
    jobs: "All Jobs",
    location: "Accessory",
    armorLevel: "1",
    upgradeTicket: "Imperial Upgrade Ticket",
  },
  {
    id: 490018,
    name: "Imperial Magic Ring [1]",
    flavor: "Imperial ring for the magic set.",
    effects: ["ASPD +5%", "Variable Cast Time -7%", "Magic damage +7% vs all elements"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "8",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "125",
    jobs: "All Jobs",
    location: "Accessory",
    armorLevel: "1",
    upgradeTicket: "Imperial Upgrade Ticket",
  },
];

type ImperialBody = {
  id: number;
  name: string;
  jobs: string;
  defense: "120" | "90";
  focus: string;
};

/** Class-specific Imperial body armor — Imperial trader (Clana Nemieri Rebellion Base). See iRO Wiki: Imperial Equipment. */
const IMPERIAL_BODIES: readonly ImperialBody[] = [
  { id: 450053, name: "Imperial Knight Armor [1]", jobs: "Rune Knight classes", defense: "120", focus: "Ignition Break (Attack set)" },
  { id: 450052, name: "Imperial Breath Armor [1]", jobs: "Rune Knight classes", defense: "120", focus: "Dragon Breath / Dragon Water Breath (Attack set)" },
  { id: 450054, name: "Imperial Spear Armor [1]", jobs: "Royal Guard classes", defense: "120", focus: "Cannon Spear (Attack set)" },
  { id: 450055, name: "Imperial Genesis Armor [1]", jobs: "Royal Guard classes", defense: "120", focus: "Genesis Ray (Magic garment / boots / ring)" },
  { id: 450076, name: "Imperial Crimson Robe [1]", jobs: "Warlock classes", defense: "90", focus: "Crimson Rock (Magic set)" },
  { id: 450077, name: "Imperial Frost Robe [1]", jobs: "Warlock classes", defense: "90", focus: "Jack Frost (Magic set)" },
  { id: 450078, name: "Imperial Psychic Robe [1]", jobs: "Sorcerer classes", defense: "90", focus: "Psychic Wave (Magic set)" },
  { id: 450079, name: "Imperial Dust Robe [1]", jobs: "Sorcerer classes", defense: "90", focus: "Diamond Dust (Magic set)" },
  { id: 450056, name: "Imperial Sharp Suit [1]", jobs: "Ranger classes", defense: "90", focus: "Focused Arrow Strike (Attack set)" },
  { id: 450057, name: "Imperial Aim Suit [1]", jobs: "Ranger classes", defense: "90", focus: "Aimed Bolt (Attack set)" },
  { id: 450058, name: "Imperial Severe Suit [1]", jobs: "Maestro / Wanderer classes", defense: "90", focus: "Severe Rainstorm (Attack set)" },
  { id: 450059, name: "Imperial Reverberation Suit [1]", jobs: "Maestro / Wanderer classes", defense: "90", focus: "Reverberation (Magic set)" },
  { id: 450064, name: "Imperial Tornado Armor [1]", jobs: "Mechanic classes", defense: "90", focus: "Axe Tornado (Attack set)" },
  { id: 450065, name: "Imperial Vulcan Armor [1]", jobs: "Mechanic classes", defense: "90", focus: "Vulcan Arm (Attack set)" },
  { id: 450066, name: "Imperial Cart Cannon Suit [1]", jobs: "Geneticist classes", defense: "90", focus: "Cart Cannon (Attack set)" },
  { id: 450067, name: "Imperial Cart Tornado Suit [1]", jobs: "Geneticist classes", defense: "90", focus: "Cart Tornado (Attack set)" },
  { id: 450068, name: "Imperial Rolling Suit [1]", jobs: "Guillotine Cross classes", defense: "90", focus: "Rolling Cutter (Attack set)" },
  { id: 450069, name: "Imperial Assassin Suit [1]", jobs: "Guillotine Cross classes", defense: "90", focus: "Critical / physical (Attack set)" },
  { id: 450070, name: "Imperial Fatal Suit [1]", jobs: "Shadow Chaser classes", defense: "90", focus: "Fatal Menace (Attack set)" },
  { id: 450071, name: "Imperial Stalker Suit [1]", jobs: "Shadow Chaser classes", defense: "90", focus: "Meteor Storm (Magic set)" },
  { id: 450061, name: "Imperial Duple Robe [1]", jobs: "Arch Bishop classes", defense: "90", focus: "Duple Light (Attack set)" },
  { id: 450060, name: "Imperial Adora Robe [1]", jobs: "Arch Bishop classes", defense: "90", focus: "Adoramus (Magic set)" },
  { id: 450062, name: "Imperial Knuckle Suit [1]", jobs: "Sura classes", defense: "90", focus: "Knuckle Arrow (Attack set)" },
  { id: 450063, name: "Imperial Tiger Cannon Suit [1]", jobs: "Sura classes", defense: "90", focus: "Tiger Cannon (Attack set)" },
  { id: 450081, name: "Imperial Full Moon Suit [1]", jobs: "Star Emperor classes", defense: "90", focus: "Full Moon Kick (Attack set)" },
  { id: 450080, name: "Imperial Sun Suit [1]", jobs: "Star Emperor classes", defense: "90", focus: "Solar Explosion (Attack set)" },
  { id: 450085, name: "Imperial Curse Robe [1]", jobs: "Soul Reaper classes", defense: "90", focus: "Curse Explosion (Magic set)" },
  { id: 450084, name: "Imperial Eswoo Robe [1]", jobs: "Soul Reaper classes", defense: "90", focus: "Eswoo (Magic set)" },
  { id: 450083, name: "Imperial Kunai Suit [1]", jobs: "Ninja classes", defense: "90", focus: "Kunai Splash (Attack set)" },
  { id: 450082, name: "Imperial Ninja Suit [1]", jobs: "Ninja classes", defense: "90", focus: "Magic ninja skills (Magic set)" },
  { id: 450074, name: "Imperial Trip Suit [1]", jobs: "Rebel classes", defense: "90", focus: "Round Trip (Attack set)" },
  { id: 450075, name: "Imperial Fire Rain Suit [1]", jobs: "Rebel classes", defense: "90", focus: "Fire Rain (Attack set)" },
  { id: 450123, name: "Imperial Super Novice Suit [1]", jobs: "Novice / Super Novice classes", defense: "90", focus: "Physical Super Novice (Attack set)" },
  { id: 450124, name: "Imperial Super Novice Robe [1]", jobs: "Novice / Super Novice classes", defense: "90", focus: "Magical Super Novice (Magic set)" },
  { id: 450072, name: "Imperial Picky Robe [1]", jobs: "Summoner (Doram) classes", defense: "90", focus: "Picky Peck (Attack set)" },
  { id: 450073, name: "Imperial Catnip Robe [1]", jobs: "Summoner (Doram) classes", defense: "90", focus: "Catnip Meteor (Magic set)" },
];

function imperialBody(p: ImperialBody): RoArmourPiece {
  const short = p.name.replace(" [1]", "");
  return {
    id: p.id,
    name: p.name,
    flavor: `${short} — exchanged from Imperial trader (Clana Nemieri Rebellion Base) for Schwartz's Honor Tokens.`,
    effects: [
      `Class / skill focus: ${p.focus}.`,
      "Four-piece Imperial bonuses use the matching Attack or Magic manteau, boots, and ring (see iRO Wiki: Imperial Equipment).",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: p.defense,
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "125",
    jobs: p.jobs,
    location: "Body",
    armorLevel: "1",
    upgradeTicket: "Imperial Upgrade Ticket",
  };
}

/** Full Imperial armour list: shared slots first, then every class body armor. */
export const IMPERIAL_ARMOUR_PIECES: readonly RoArmourPiece[] = [...IMPERIAL_SHARED, ...IMPERIAL_BODIES.map(imperialBody)];
