import type { RoArmourPiece } from "./msq-types";

/**
 * Direction of Prayer (Episode 18) Gray Wolf set — Divine Pride (iRO) item pages.
 * Display order matches the user's ID list (Suit branch + accessories, then Robe branch).
 */
export const GRAY_WOLF_ARMOUR_PIECES: readonly RoArmourPiece[] = [
  {
    id: 450177,
    name: "Gray Wolf Suit [1]",
    flavor: "Armor given to those recognized by the Gray Wolf Tribe.",
    effects: [
      "ATK +130",
      "ATK +15 for every 2 refine levels",
      "If refined to +7 or higher: ASPD +15%",
      "Set with Gray Wolf Manteau [1]: ATK +50",
      "Set with Gray Wolf Muffler [1]: Reduces global skill delay by 10%",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: "160",
    weight: "100",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "190",
    jobs: "All Jobs",
    location: "Body",
    armorLevel: "1",
  },
  {
    id: 480090,
    name: "Gray Wolf Muffler [1]",
    flavor: "Muffler given to those recognized by the Gray Wolf Tribe.",
    effects: [
      "MaxHP +1,500",
      "MaxHP +100 for every 2 refine levels",
      "If refined to +7 or higher: Variable Cast Time -7%",
      "Set with Gray Wolf Boots [1]: Long-ranged Physical damage +7%",
      "Set with Gray Wolf Shoes [1]: All property Magical damage +15%",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "70",
    weight: "90",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "190",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "1",
  },
  {
    id: 470087,
    name: "Gray Wolf Boots [1]",
    flavor: "Boots given to those recognized by the Gray Wolf Tribe.",
    effects: [
      "MaxSP +300",
      "MaxSP +50 for every 2 refine levels",
      "If refined to +7 or higher: Long-ranged Physical damage +7%",
      "Set with Gray Wolf Suit [1]: ATK +7%",
      "Set with Gray Wolf Robe [1]: ASPD +7%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "70",
    weight: "50",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "190",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "1",
  },
  {
    id: 490106,
    name: "Gray Wolf Pendant [1]",
    flavor: "Pendant given to those recognized by the Gray Wolf Tribe.",
    effects: ["ATK +7%", "MaxHP +5%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "190",
    jobs: "All Jobs",
    location: "Accessory (Right)",
    armorLevel: "1",
  },
  {
    id: 490108,
    name: "Gray Wolf Earring [1]",
    flavor: "Earring given to those recognized by the Gray Wolf Tribe.",
    effects: ["MATK +7%", "MaxHP +5%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "190",
    jobs: "All Jobs",
    location: "Accessory (Right)",
    armorLevel: "1",
  },
  {
    id: 450178,
    name: "Gray Wolf Robe [1]",
    flavor: "Robe given to those recognized by the Gray Wolf Tribe.",
    effects: [
      "MATK +130",
      "MATK +15 for every 2 refine levels",
      "If refined to +7 or higher: Variable Cast Time -15%",
      "Set with Gray Wolf Manteau [1]: ASPD +10%",
      "Set with Gray Wolf Muffler [1]: MATK +50",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: "160",
    weight: "100",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "190",
    jobs: "All Jobs",
    location: "Body",
    armorLevel: "1",
  },
  {
    id: 480091,
    name: "Gray Wolf Manteau [1]",
    flavor: "Manteau given to those recognized by the Gray Wolf Tribe.",
    effects: [
      "MaxHP +2,500",
      "MaxHP +150 for every 2 refine levels",
      "If refined to +7 or higher: ASPD +7%",
      "Set with Gray Wolf Boots [1]: Critical damage +15%",
      "Set with Gray Wolf Shoes [1]: Variable Cast Time -15%",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "70",
    weight: "90",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "190",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "1",
  },
  {
    id: 470088,
    name: "Gray Wolf Shoes [1]",
    flavor: "Shoes given to those recognized by the Gray Wolf Tribe.",
    effects: [
      "MaxSP +250",
      "MaxSP +20 for every 2 refine levels",
      "If refined to +7 or higher: All property Magical damage +7%",
      "Set with Gray Wolf Suit [1]: MaxSP +7%",
      "Set with Gray Wolf Robe [1]: MATK +7%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "70",
    weight: "50",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "190",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "1",
  },
  {
    id: 490107,
    name: "Gray Wolf Ring [1]",
    flavor: "Ring given to those recognized by the Gray Wolf Tribe.",
    effects: ["ATK +7%", "MaxSP +5%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "190",
    jobs: "All Jobs",
    location: "Accessory (Left)",
    armorLevel: "1",
  },
  {
    id: 490109,
    name: "Gray Wolf Necklace [1]",
    flavor: "Necklace given to those recognized by the Gray Wolf Tribe.",
    effects: ["MATK +7%", "MaxSP +5%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "190",
    jobs: "All Jobs",
    location: "Accessory (Left)",
    armorLevel: "1",
  },
];
