import type { RoArmourPiece } from "./msq-types";

/** Snow Flower armour (level 210) — Ice Castle exchange, 100 Snow Flower Petals per piece (iRO Wiki Issgard). */
export const SNOW_FLOWER_ARMOUR_PIECES: readonly RoArmourPiece[] = [
  {
    id: 450206,
    name: "Snow Flower Armor [1]",
    flavor:
      "Armor crafted from the ground petals of the snowdrops found in Isgard. You can equip it with ice flower magic stones which possess special magical powers, to enhance its abilities.",
    effects: [
      "ATK +130",
      "ATK +15 per 2 refine levels",
      "If +7 or higher: ASPD +15%",
      "If +9 or higher: P.Atk +2",
      "Set with Snow Flower Manteau [1]: ATK +50",
      "Set with Snow Flower Muffler [1]: global skill delay -10%",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: "150",
    weight: "80",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "210",
    jobs: "All Jobs",
    location: "Body",
    armorLevel: "2",
  },
  {
    id: 450207,
    name: "Snow Flower Robe [1]",
    flavor:
      "Robe crafted from the ground petals of the snowdrops found in Isgard. You can equip it with ice flower magic stones which possess special magical powers, to enhance its abilities.",
    effects: [
      "MATK +130",
      "MATK +15 per 2 refine levels",
      "If +7 or higher: Variable Cast Time -15%",
      "If +9 or higher: S.Matk +2",
      "Set with Snow Flower Manteau [1]: ASPD +10%",
      "Set with Snow Flower Muffler [1]: MATK +50",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: "150",
    weight: "80",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "210",
    jobs: "All Jobs",
    location: "Body",
    armorLevel: "2",
  },
  {
    id: 480159,
    name: "Snow Flower Manteau [1]",
    flavor:
      "Manteau crafted from the ground petals of the snowdrops found in Isgard. You can equip it with ice flower magic stones which possess special magical powers, to enhance its abilities.",
    effects: [
      "MaxHP +2,500, MaxSP +500",
      "MaxHP +200 and MaxSP +50 per 2 refine levels",
      "If +7 or higher: ASPD +7%",
      "If +9 or higher: POW +3",
      "Set with Snow Flower Boots [1]: Critical damage +15%",
      "Set with Snow Flower Shoes [1]: Variable Cast Time -15%",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "70",
    weight: "90",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "210",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "2",
  },
  {
    id: 480160,
    name: "Snow Flower Muffler [1]",
    flavor:
      "Muffler crafted from the ground petals of the snowdrops found in Isgard. You can equip it with ice flower magic stones which possess special magical powers, to enhance its abilities.",
    effects: [
      "MaxHP +2,000, MaxSP +1,000",
      "MaxHP +150 and MaxSP +100 per 2 refine levels",
      "If +7 or higher: Variable Cast Time -7%",
      "If +9 or higher: SPL +3",
      "Set with Snow Flower Boots [1]: Long-ranged Physical damage +7%",
      "Set with Snow Flower Shoes [1]: All property Magical damage +15%",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "70",
    weight: "90",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "210",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "2",
  },
  {
    id: 470115,
    name: "Snow Flower Boots [1]",
    flavor:
      "Boots crafted from the ground petals of the snowdrops found in Isgard. You can equip it with ice flower magic stones which possess special magical powers, to enhance its abilities.",
    effects: [
      "MaxHP +8%, MaxSP +4%",
      "MaxSP +1% per 2 refine levels",
      "If +7 or higher: melee and long-ranged physical damage +7%",
      "If +9 or higher: P.Atk +2",
      "Set with Snow Flower Armor [1]: ATK +7%",
      "Set with Snow Flower Robe [1]: ASPD +7%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "70",
    weight: "50",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "210",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "2",
  },
  {
    id: 470116,
    name: "Snow Flower Shoes [1]",
    flavor:
      "Shoes crafted from the ground petals of the snowdrops found in Isgard. You can equip it with ice flower magic stones which possess special magical powers, to enhance its abilities.",
    effects: [
      "MaxHP +6%, MaxSP +6%",
      "MaxSP +1% per 2 refine levels",
      "If +7 or higher: all property Magical damage +7%",
      "If +9 or higher: S.Matk +2",
      "Set with Snow Flower Armor [1]: Variable Cast Time -7%",
      "Set with Snow Flower Robe [1]: MATK +7%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "70",
    weight: "50",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "210",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "2",
  },
  {
    id: 490176,
    name: "Snow Flower Pendant [1]",
    flavor:
      "Pendant crafted from the ground petals of the snowdrops found in Isgard. You can equip it with ice flower magic stones which possess special magical powers, to enhance its abilities.",
    effects: ["ATK +7%", "MaxHP +7%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "210",
    jobs: "All Jobs",
    location: "Accessory",
    armorLevel: "2",
  },
  {
    id: 490177,
    name: "Snow Flower Ring [1]",
    flavor:
      "Ring crafted from the ground petals of the snowdrops found in Isgard. You can equip it with ice flower magic stones which possess special magical powers, to enhance its abilities.",
    effects: ["ATK +7%", "MaxSP +7%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "210",
    jobs: "All Jobs",
    location: "Accessory",
    armorLevel: "2",
  },
  {
    id: 490179,
    name: "Snow Flower Earring [1]",
    flavor:
      "Earring crafted from the ground petals of the snowdrops found in Isgard. You can equip it with ice flower magic stones which possess special magical powers, to enhance its abilities.",
    effects: ["MATK +7%", "MaxSP +7%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "210",
    jobs: "All Jobs",
    location: "Accessory",
    armorLevel: "2",
  },
  {
    id: 490178,
    name: "Snow Flower Necklace [1]",
    flavor:
      "Necklace crafted from the ground petals of the snowdrops found in Isgard. You can equip it with ice flower magic stones which possess special magical powers, to enhance its abilities.",
    effects: ["MATK +7%", "MaxHP +7%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "210",
    jobs: "All Jobs",
    location: "Accessory",
    armorLevel: "2",
  },
];
