import type { RoArmourPiece } from "./msq-types";

/** Shared Grace garments / footwear / rings (all classes). */
const GRACE_SHARED: readonly RoArmourPiece[] = [
  {
    id: 480018,
    name: "Grace Attack Manteau [1]",
    flavor: "A noble manteau with the Rune-Midgarts crest — physical Grace set (Grace Trader, Cor).",
    effects: [
      "ASPD +7%",
      "If refined to +7 or higher: After Cast Delay -5%",
      "If refined to +9 or higher: Physical damage +10% vs all sizes",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "30",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "150",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "1",
    upgradeTicket: "Grace Upgrade Ticket",
  },
  {
    id: 480019,
    name: "Grace Magic Manteau [1]",
    flavor: "Noble manteau tuned for spellcasting — magic Grace set.",
    effects: [
      "Variable Cast Time -10%",
      "If refined to +7 or higher: After Cast Delay -5%",
      "If refined to +9 or higher: All elemental magic damage +10%",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "30",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "150",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "1",
    upgradeTicket: "Grace Upgrade Ticket",
  },
  {
    id: 470020,
    name: "Grace Attack Boots [1]",
    flavor: "Grace footwear for the physical attack branch.",
    effects: [
      "ATK +20",
      "HIT +20",
      "If refined to +7 or higher: Fixed Cast Time -0.5 sec",
      "If refined to +9 or higher: Long-ranged physical damage +10%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "30",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "150",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "1",
    upgradeTicket: "Grace Upgrade Ticket",
  },
  {
    id: 470021,
    name: "Grace Magic Boots [1]",
    flavor: "Grace footwear for the magic branch.",
    effects: [
      "MATK +20",
      "FLEE +20",
      "If refined to +7 or higher: Fixed Cast Time -0.5 sec",
      "If refined to +9 or higher: All elemental magic damage +10%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "30",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "150",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "1",
    upgradeTicket: "Grace Upgrade Ticket",
  },
  {
    id: 490019,
    name: "Grace Attack Ring [1]",
    flavor: "Grace ring for the physical attack set (right accessory).",
    effects: ["ASPD +7%", "Variable Cast Time -10%", "Critical Damage +10%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "10",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "150",
    jobs: "All Jobs",
    location: "Accessory",
    armorLevel: "1",
    upgradeTicket: "Grace Upgrade Ticket",
  },
  {
    id: 490020,
    name: "Grace Magic Ring [1]",
    flavor: "Grace ring for the magic set (right accessory).",
    effects: ["ASPD +7%", "Variable Cast Time -10%", "All elemental magic damage +10%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "10",
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "150",
    jobs: "All Jobs",
    location: "Accessory",
    armorLevel: "1",
    upgradeTicket: "Grace Upgrade Ticket",
  },
];

type GraceBody = {
  id: number;
  name: string;
  jobs: string;
  defense: "130" | "100";
  focus: string;
};

/** Class-specific Grace body armor — Grace Trader (sp_cor) after Illusion MSQ. See iRO Wiki: Grace Equipment. */
const GRACE_BODIES: readonly GraceBody[] = [
  { id: 450087, name: "Grace Knight Armor [1]", jobs: "Rune Knight classes", defense: "130", focus: "Ignition Break (Attack set)" },
  { id: 450086, name: "Grace Breath Armor [1]", jobs: "Rune Knight classes", defense: "130", focus: "Dragon Breath / Dragon Water Breath (Attack set)" },
  { id: 450088, name: "Grace Spear Armor [1]", jobs: "Royal Guard classes", defense: "130", focus: "Cannon Spear (Attack set)" },
  { id: 450089, name: "Grace Genesis Armor [1]", jobs: "Royal Guard classes", defense: "130", focus: "Genesis Ray (Magic garment / boots / ring)" },
  { id: 450110, name: "Grace Crimson Robe [1]", jobs: "Warlock classes", defense: "100", focus: "Crimson Rock (Magic set)" },
  { id: 450111, name: "Grace Frost Robe [1]", jobs: "Warlock classes", defense: "100", focus: "Jack Frost (Magic set)" },
  { id: 450112, name: "Grace Psychic Robe [1]", jobs: "Sorcerer classes", defense: "100", focus: "Psychic Wave (Magic set)" },
  { id: 450113, name: "Grace Dust Robe [1]", jobs: "Sorcerer classes", defense: "100", focus: "Diamond Dust (Magic set)" },
  { id: 450090, name: "Grace Sharp Suit [1]", jobs: "Ranger classes", defense: "100", focus: "Focused Arrow Strike (Attack set)" },
  { id: 450091, name: "Grace Aim Suit [1]", jobs: "Ranger classes", defense: "100", focus: "Aimed Bolt (Attack set)" },
  { id: 450092, name: "Grace Severe Suit [1]", jobs: "Maestro / Wanderer classes", defense: "100", focus: "Severe Rainstorm (Attack set)" },
  { id: 450093, name: "Grace Reverberation Suit [1]", jobs: "Maestro / Wanderer classes", defense: "100", focus: "Reverberation (Magic set)" },
  { id: 450098, name: "Grace Tornado Armor [1]", jobs: "Mechanic classes", defense: "100", focus: "Axe Tornado (Attack set)" },
  { id: 450099, name: "Grace Vulcan Armor [1]", jobs: "Mechanic classes", defense: "100", focus: "Vulcan Arm (Attack set)" },
  { id: 450100, name: "Grace Cart Cannon Suit [1]", jobs: "Geneticist classes", defense: "100", focus: "Cart Cannon (Attack set)" },
  { id: 450101, name: "Grace Cart Tornado Suit [1]", jobs: "Geneticist classes", defense: "100", focus: "Cart Tornado (Attack set)" },
  { id: 450102, name: "Grace Rolling Suit [1]", jobs: "Guillotine Cross classes", defense: "100", focus: "Rolling Cutter (Attack set)" },
  { id: 450103, name: "Grace Assassin Suit [1]", jobs: "Guillotine Cross classes", defense: "100", focus: "Critical / physical (Attack set)" },
  { id: 450104, name: "Grace Fatal Suit [1]", jobs: "Shadow Chaser classes", defense: "100", focus: "Fatal Menace (Attack set)" },
  { id: 450105, name: "Grace Stalker Suit [1]", jobs: "Shadow Chaser classes", defense: "100", focus: "Meteor Storm (Magic set)" },
  { id: 450095, name: "Grace Duple Robe [1]", jobs: "Arch Bishop classes", defense: "100", focus: "Duple Light (Attack set)" },
  { id: 450094, name: "Grace Adora Robe [1]", jobs: "Arch Bishop classes", defense: "100", focus: "Adoramus (Magic set)" },
  { id: 450096, name: "Grace Knuckle Suit [1]", jobs: "Sura classes", defense: "100", focus: "Knuckle Arrow (Attack set)" },
  { id: 450097, name: "Grace Tiger Cannon Suit [1]", jobs: "Sura classes", defense: "100", focus: "Tiger Cannon (Attack set)" },
  { id: 450115, name: "Grace Full Moon Suit [1]", jobs: "Star Emperor classes", defense: "100", focus: "Full Moon Kick (Attack set)" },
  { id: 450114, name: "Grace Sun Suit [1]", jobs: "Star Emperor classes", defense: "100", focus: "Solar Explosion (Attack set)" },
  { id: 450119, name: "Grace Curse Robe [1]", jobs: "Soul Reaper classes", defense: "100", focus: "Curse Explosion (Magic set)" },
  { id: 450118, name: "Grace Eshwoo Robe [1]", jobs: "Soul Reaper classes", defense: "100", focus: "Eswoo (Magic set)" },
  { id: 450117, name: "Grace Kunai Suit [1]", jobs: "Ninja classes", defense: "100", focus: "Kunai Splash (Attack set)" },
  { id: 450116, name: "Grace Ninja Suit [1]", jobs: "Ninja classes", defense: "100", focus: "Magic ninja skills (Magic set)" },
  { id: 450108, name: "Grace Trip Suit [1]", jobs: "Rebel classes", defense: "100", focus: "Round Trip (Attack set)" },
  { id: 450109, name: "Grace Fire Rain Suit [1]", jobs: "Rebel classes", defense: "100", focus: "Fire Rain (Attack set)" },
  { id: 450125, name: "Grace Super Novice Suit [1]", jobs: "Novice / Super Novice classes", defense: "100", focus: "Physical Super Novice (Attack set)" },
  { id: 450126, name: "Grace Super Novice Robe [1]", jobs: "Novice / Super Novice classes", defense: "100", focus: "Magical Super Novice (Magic set)" },
  { id: 450106, name: "Grace Picky Robe [1]", jobs: "Summoner (Doram) classes", defense: "100", focus: "Picky Peck (Attack set)" },
  { id: 450107, name: "Grace Catnip Robe [1]", jobs: "Summoner (Doram) classes", defense: "100", focus: "Catnip Meteor (Magic set)" },
];

function graceBody(p: GraceBody): RoArmourPiece {
  const short = p.name.replace(" [1]", "");
  return {
    id: p.id,
    name: p.name,
    flavor: `${short} — exchanged from Grace Trader in Cor (sp_cor) for Mysterious Components after the Illusion questline.`,
    effects: [
      `Class / skill focus: ${p.focus}.`,
      "Four-piece Grace bonuses use the matching Attack or Magic manteau, boots, and ring (see iRO Wiki: Grace Equipment).",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: p.defense,
    weight: "0",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "150",
    jobs: p.jobs,
    location: "Body",
    armorLevel: "1",
    upgradeTicket: "Grace Upgrade Ticket",
  };
}

export const GRACE_ARMOUR_PIECES: readonly RoArmourPiece[] = [...GRACE_SHARED, ...GRACE_BODIES.map(graceBody)];
