import type { RoArmourPiece } from "./msq-types";

/** Legacy of the Wise One (17.2) Automatic line — iRO Wiki + Divine Pride (iRO). */
export const AUTOMATIC_ARMOUR_PIECES: readonly RoArmourPiece[] = [
  {
    id: 450127,
    name: "Automatic Armor Type A [1]",
    flavor:
      "Combat armor improved with the technology of Barmund Mansion, Type A. Various modules can be used for additional abilities.",
    effects: [
      "ATK +125",
      "ATK +10 for every 2 refine levels",
      "If refined to +7 or higher: ASPD +15%",
      "With Automatic Engine Wing Type A: ATK +50",
      "With Illusion Engine Wing Type B: post-skill delay -10%",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: "135",
    weight: "100",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "160",
    jobs: "All Jobs",
    location: "Body",
    armorLevel: "1",
    upgradeTicket: "Automatic Upgrade Cube",
  },
  {
    id: 450128,
    name: "Automatic Armor Type B [1]",
    flavor:
      "Combat armor improved with the technology of Barmund Mansion, Type B. Various modules can be used for additional abilities.",
    effects: [
      "MATK +125",
      "MATK +10 for every 2 refine levels",
      "If refined to +7 or higher: Variable Cast Time -15%",
      "With Automatic Engine Wing Type A: ASPD +10%",
      "With Illusion Engine Wing Type B: MATK +50",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: "135",
    weight: "100",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "160",
    jobs: "All Jobs",
    location: "Body",
    armorLevel: "1",
    upgradeTicket: "Automatic Upgrade Cube",
  },
  {
    id: 480020,
    name: "Automatic Engine Wing Type A [1]",
    flavor:
      "Combat engine improved with the technology of Barmund Mansion, Type A. Various modules can be used for additional abilities.",
    effects: [
      "MaxHP +1,500",
      "MaxHP +100 for every 2 refine levels",
      "If refined to +7 or higher: ASPD +7%",
      "With Automatic Leg Type A: Critical damage +15%",
      "With Automatic Leg Type B: Variable Cast Time -15%",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "70",
    weight: "90",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "160",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "1",
    upgradeTicket: "Automatic Upgrade Cube",
  },
  {
    id: 480021,
    name: "Automatic Engine Wing Type B [1]",
    flavor:
      "Combat engine improved with the technology of Barmund Mansion, Type B. Various modules can be used for additional abilities.",
    effects: [
      "MaxHP +1,500",
      "MaxHP +100 for every 2 refine levels",
      "If refined to +7 or higher: Variable Cast Time -7%",
      "With Automatic Leg Type A: Long-ranged Physical damage +7%",
      "With Automatic Leg Type B: All elemental Magic damage +15%",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "70",
    weight: "90",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "160",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "1",
    upgradeTicket: "Automatic Upgrade Cube",
  },
  {
    id: 470022,
    name: "Automatic Leg Type A [1]",
    flavor:
      "Combat boots improved with the technology of Barmund Mansion, Type A. Various modules can be used for additional abilities.",
    effects: [
      "MaxSP +250",
      "MaxSP +20 for every 2 refine levels",
      "If refined to +7 or higher: Long-ranged Physical damage +7%",
      "With Automatic Armor Type A: ATK +7%",
      "With Automatic Armor Type B: ASPD +7%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "70",
    weight: "50",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "160",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "1",
    upgradeTicket: "Automatic Upgrade Cube",
  },
  {
    id: 470023,
    name: "Automatic Leg Type B [1]",
    flavor:
      "Combat boots improved with the technology of Barmund Mansion, Type B. Various modules can be used for additional abilities.",
    effects: [
      "MaxSP +250",
      "MaxSP +20 for every 2 refine levels",
      "If refined to +7 or higher: All elemental Magic damage +7%",
      "With Automatic Armor Type A: MaxSP +7%",
      "With Automatic Armor Type B: MATK +7%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "70",
    weight: "50",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "160",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "1",
    upgradeTicket: "Automatic Upgrade Cube",
  },
  {
    id: 490024,
    name: "Automatic Booster R [1]",
    flavor:
      "Battle component improved with the technology of Barmund Mansion. Various modules can be used for additional abilities.",
    effects: ["ATK +5%", "MaxHP +5%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "160",
    jobs: "All Jobs",
    location: "Accessory (Right)",
    armorLevel: "1",
    upgradeTicket: "Automatic Upgrade Cube",
  },
  {
    id: 490025,
    name: "Automatic Booster L [1]",
    flavor:
      "Battle component improved with the technology of Barmund Mansion. Various modules can be used for additional abilities.",
    effects: ["ATK +5%", "MaxSP +5%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "160",
    jobs: "All Jobs",
    location: "Accessory (Left)",
    armorLevel: "1",
    upgradeTicket: "Automatic Upgrade Cube",
  },
  {
    id: 490026,
    name: "Automatic Battle Chip R [1]",
    flavor:
      "Battle chip improved with the technology of Barmund Mansion. Various modules can be used for additional abilities.",
    effects: ["MATK +5%", "MaxHP +5%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "160",
    jobs: "All Jobs",
    location: "Accessory (Right)",
    armorLevel: "1",
    upgradeTicket: "Automatic Upgrade Cube",
  },
  {
    id: 490027,
    name: "Automatic Battle Chip L [1]",
    flavor:
      "Battle chip improved with the technology of Barmund Mansion. Various modules can be used for additional abilities.",
    effects: ["MATK +5%", "MaxSP +5%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "160",
    jobs: "All Jobs",
    location: "Accessory (Left)",
    armorLevel: "1",
    upgradeTicket: "Automatic Upgrade Cube",
  },
];
