import type { RoArmourPiece } from "./msq-types";

/**
 * Glacier armour (level 230) — Issgard / Free-to-play Equipment Lv 210 section lists Glacier weapons
 * alongside Snow Flower armour; armour stats from Divine Pride (iRO).
 */
export const GLACIER_ARMOUR_PIECES: readonly RoArmourPiece[] = [
  {
    id: 450264,
    name: "Glacier Armor [1]",
    flavor: "Heavy physical armour of the Glacier line.",
    effects: [
      "ATK +120; every 2 refine: ATK +15, DEF +15",
      "If +7 or higher: melee & ranged physical damage +5%, ASPD +10%",
      "If +9 or higher: P.Atk +3, additional ASPD +5%",
      "If +10 or higher: DEF +100, global cooldown -5%",
      "With Glacier Manteau [1]: ATK +50",
      "Grade D/C bonuses: POW/CON, ATK%, P.Atk (see in-game)",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: "168",
    weight: "240",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "230",
    jobs: "All Jobs",
    location: "Body",
    armorLevel: "2",
  },
  {
    id: 450265,
    name: "Glacier Robe [1]",
    flavor: "Magical robe of the Glacier line.",
    effects: [
      "MATK +120; every 2 refine: MATK +15, DEF +15",
      "If +7 or higher: all property magical damage +5%, Variable Cast Time -10%",
      "If +9 or higher: S.Matk +3, additional Variable Cast Time -5%",
      "If +10 or higher: DEF +100, global cooldown -5%",
      "With Glacier Muffler [1]: MATK +50",
      "Grade D/C bonuses: SPL/CON, MATK%, S.Matk (see in-game)",
    ],
    equipType: "Armor",
    subtype: "Armor",
    defense: "120",
    weight: "120",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "230",
    jobs: "All Jobs",
    location: "Body",
    armorLevel: "2",
  },
  {
    id: 450266,
    name: "Glacier Manteau [1]",
    flavor: "Glacier manteau tuned for physical builds.",
    effects: [
      "MaxHP +2,500, MaxSP +500",
      "Every 2 refine: MaxHP +200, MaxSP +50",
      "If +7 or higher: ASPD +7%",
      "If +9 or higher: POW +3",
      "If +10 or higher: Variable Cast Time -5%",
      "With Glacier Boots [1]: melee & ranged physical damage +15%",
      "With Glacier Pendant + Ring: extra physical set bonuses (see in-game)",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "112",
    weight: "160",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "230",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "2",
  },
  {
    id: 450267,
    name: "Glacier Muffler [1]",
    flavor: "Glacier muffler tuned for magical builds.",
    effects: [
      "MaxHP +2,000, MaxSP +1,000",
      "Every 2 refine: MaxHP +150, MaxSP +100",
      "If +7 or higher: Variable Cast Time -7%",
      "If +9 or higher: SPL +3",
      "If +10 or higher: ASPD +5%",
      "With Glacier Shoes [1]: all property magical damage +15%",
      "With Glacier Earring + Necklace: extra magical set bonuses (see in-game)",
    ],
    equipType: "Armor",
    subtype: "Garment",
    defense: "80",
    weight: "80",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "230",
    jobs: "All Jobs",
    location: "Garment",
    armorLevel: "2",
  },
  {
    id: 470196,
    name: "Glacier Boots [1]",
    flavor: "Physical-route Glacier footwear.",
    effects: [
      "MaxHP +8%, MaxSP +4%",
      "Every 2 refine: MaxSP +1%, DEF +15",
      "If +7 or higher: melee & ranged physical damage +7%",
      "If +9 or higher: P.Atk +3",
      "If +10 or higher: DEF +100, ASPD +7%",
      "With Glacier Armor [1]: ATK +7%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "98",
    weight: "200",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "230",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "2",
  },
  {
    id: 450268,
    name: "Glacier Shoes [1]",
    flavor: "Magical-route Glacier footwear.",
    effects: [
      "MaxHP +6%, MaxSP +6%",
      "Every 2 refine: MaxSP +1%, DEF +15",
      "If +7 or higher: all property magical damage +7%",
      "If +9 or higher: S.Matk +3",
      "If +10 or higher: DEF +100, Variable Cast Time -7%",
      "With Glacier Robe [1]: MATK +7%",
    ],
    equipType: "Armor",
    subtype: "Shoes",
    defense: "70",
    weight: "100",
    property: "Neutral",
    slots: "[1]",
    refineable: "Yes",
    requiredLevel: "230",
    jobs: "All Jobs",
    location: "Shoes",
    armorLevel: "2",
  },
  {
    id: 490328,
    name: "Glacier Pendant [1]",
    flavor: "Physical Glacier accessory (right).",
    effects: [
      "ATK +8%, MaxHP +7%",
      "With Glacier Ring: DEF +50",
      "Tri-piece sets with Armor / Manteau / Boots add FCT, ATK%, ranged/melee damage, P.Atk & DEF (see in-game)",
    ],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "230",
    jobs: "All Jobs",
    location: "Accessory (Right)",
    armorLevel: "2",
  },
  {
    id: 490327,
    name: "Glacier Ring [1]",
    flavor: "Physical Glacier accessory (left).",
    effects: ["ATK +8%, MaxSP +7%"],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "230",
    jobs: "All Jobs",
    location: "Accessory (Left)",
    armorLevel: "2",
  },
  {
    id: 490329,
    name: "Glacier Earring [1]",
    flavor: "Magical Glacier accessory (left).",
    effects: [
      "MATK +8%, MaxSP +7%",
      "With Glacier Necklace: DEF +50",
      "Tri-piece sets with Robe / Muffler / Shoes add FCT, MATK%, magic damage, S.Matk & DEF (see in-game)",
    ],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "230",
    jobs: "All Jobs",
    location: "Accessory (Left)",
    armorLevel: "2",
  },
  {
    id: 490330,
    name: "Glacier Necklace [1]",
    flavor: "Magical Glacier accessory (right).",
    effects: [
      "MATK +8%, MaxHP +7%",
      "With Glacier Earring and Robe: fixed cast time reduction, MATK +5%",
      "With Glacier Earring and Muffler: all property magical damage +5%",
      "With Glacier Earring and Shoes: S.Matk +3, DEF +30",
    ],
    equipType: "Armor",
    subtype: "Accessory",
    defense: "0",
    weight: "10",
    property: "Neutral",
    slots: "[1]",
    refineable: "No",
    requiredLevel: "230",
    jobs: "All Jobs",
    location: "Accessory (Right)",
    armorLevel: "2",
  },
];
